### ISSUE TITLE
Yo atvaark

### ISSUE THREAD

**Issue by dotbear** [Atvaark/VermintideBundleTool#1]
Great work!
I've got the files unpacked and such, but I am puzzled by how to open the .strings files. I've got them open as a UTF-8 encoding on sublime, but it still doesn't look right.

Do you know of any software that will read these?

**Comment by Atvaark** [comment]
What do you mean by 'it still doesn't look right.'?

**Comment by dotbear** [comment]
Sorry, I am very new to unpacking game files. This is what I get when opening it:
![image](https://cloud.githubusercontent.com/assets/2480963/10841147/ba5732c2-7ede-11e5-9471-3e18a43d09f1.png)

When I open the file with my texteditor, I get to see the strings, but they are all in a big pile with not order: 
![image](https://cloud.githubusercontent.com/assets/2480963/10841169/e6894b82-7ede-11e5-80bb-7cecc09f0da2.png)

**Comment by Atvaark** [comment]
That's because _.strings_ files aren't simple text files. They also contain information about how many strings are in the file and for each string there is an _ID_ (So the game knows which string to load and display).

As you can see the actual text is just separated by NULLs.

I quickly wrote a template to parse the Bitsquid _.strings_ files. All you have to do is to write a script that implements the extraction algorithm.
https://gist.github.com/Atvaark/8e05e265c37377cf555f

**Comment by dotbear** [comment]
Thank you so much! I understand that I'm probably asking really stupid questions, but it means the world that you would take your time to reply :)

I'll check out your script!

EDIT: Alright, so I've got no idea where to go with this script. C++ isn't a language I've touched very much :(
EDIT: I managed to export the strings using a tool I found for the bitsquid engine :)

**Comment by Atvaark** [comment]
It's not a script to unpack or dump. It is just the instructions to parse the files correctly.

**Comment by dotbear** [comment]
Yes ofcourse, my bad. I can see now what you mean about the file being a table with IDs.
Now my next issue is the .unit files, but I guess I need to get a hold of the Stingray engine for those.
